FROM openjdk:11
COPY target/Currency-Conversion-Service-0.0.1-SNAPSHOT.jar Currency-Conversion-Service-0.0.1-SNAPSHOT.jar
EXPOSE 8100
ENTRYPOINT ["java","-jar", "Currency-Conversion-Service-0.0.1-SNAPSHOT.jar"]